name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "3e543878-39c6-457f-9fe1-c4ad31b8f9bc"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV
id = "d51ec79b447e4b3297c21ce036f4f422"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
